### ISSUE TITLE
Emails wont display when switching from company, unless refreshed

### ISSUE THREAD

**Issue by Ivnmza** [Jobascript/Jobascript#31]
To recreate:

On homepage: Follow Github
On Comm tab: Click Auth + Emails button
On Comm tab: Click Auth + Emails button again
Should see primitive emails
Follow Trello
Click Auth + Emails button two times again, will NOT show here as expected
Refresh page, then click Auth + Emails two times again, should appear

**Comment by Ivnmza** [comment]
To recreate:

1. On homepage: Follow Github
2. On Comm tab: Click Auth + Emails button
3. On Comm tab: Click Auth + Emails button again
4. Should see primitive emails
5. Follow Trello
6. Click Auth + Emails button two times again, will NOT show here as expected
7. Refresh page, then click Auth + Emails two times again, should appear

**Comment by jakech** [comment]
Fix with #46
